### ISSUE TITLE
Cannot create "chart" visualisations for "Google spreadsheet" data source

### ISSUE THREAD

**Issue by shyamgopal** [EverythingMe/redash#574] opened 2015-09-25 05:15 UTC
Cannot create "chart" visualisations for "Google spreadsheet" data source.

Details:
1) Created a Google spreadsheet with first column as X: 1, 2, 3 ... 42,  second column as Y: 1, 4, 9, ...42^2
2) Successfully imported the data into redash. "Table" and "Pivot table" both successfully populated with data. 
3) Can create "counter" visualisation from the data
4) Cannot create any "chart" visualisation from the same data

**Comment by arikfr** [comment] 2015-09-25 05:27
Can you share the spreadsheet URL so I can try to reproduce?

**Comment by shyamgopal** [comment] 2015-09-25 06:02
Is it ok if I email you the details from my personal email id ?

**Comment by arikfr** [comment] 2015-09-25 06:09
Sure. Arik@arikfr.com

**Comment by arikfr** [comment] 2015-09-25 13:21
Looks like the problem is due to the fact the Google Spreadsheets returning all values as strings. We need to cast them into the appropriate types to use in charts.

Maybe we should just cast all values we pass to the chart renderer into numbers, to avoid cases like this (the other option is to cast only the values we get from Spreadsheets in the query runner).

**Comment by shyamgopal** [comment] 2015-09-26 04:42
Isn't  "_guess_type()" method in "google_spreadsheets.py" already supposed to that ?

**Comment by arikfr** [comment] 2015-09-26 20:54
The type is used only in the table visualization but not in the other ones.

**Comment by arikfr** [comment] 2015-10-11 08:28
Fixed in #589.

**Closed by arikfr** 2015-10-11 08:28 UTC
