### ISSUE TITLE
Query bigquery - Error running query

### ISSUE THREAD

**Issue by may215** [EverythingMe/redash#497] opened 2015-07-16 11:11 UTC
The query is:
select count(*) from TEST.table
Error running query: [["asn1 encoding routines","ASN1_CHECK_TLEN","wrong tag"],["asn1 encoding routines","ASN1_ITEM_EX_D2I","nested asn1 error"]]

Redash version: 0.6.3
Running on ubuntu 14.04 on google cloud.
Any Ideas?

**Comment by arikfr** [comment] 2015-07-16 11:40
Judging by the error message, it looks like some issue with ssl certificates. 

Did you setup the BigQuery connection using a service account or instance based permissions?

**Comment by may215** [comment] 2015-07-17 08:27
Hi,
I did set up using service account, I am using the same configuration properties(service account, project, and pem private key) with other on premise solution we have in the company, therefor, I guess the credentials are the right ones. 

Do you have any suggestions?

**Comment by alexanderlz** [comment] 2015-07-17 18:38
Hi Meir,

you mentioned "...pem private key...". Are you sure you are using .pem?
Cause the private key in BigQuery datasource should be .p12 file (obtained when creating google service  account)

**Comment by arikfr** [comment] 2015-07-19 06:44
@may215 it's most likely some issue with the certificate file. Googling around, I stumbled at this [question on StackOverflow](http://stackoverflow.com/questions/27483589/google-api-p12-key-not-readable-error0d0680a8asn1-encoding-routinesasn1-chec), where they had the same error message when using a certificate file that was downloaded on a Windows machine, which might cause encoding issues when moving around the file.

Any chance something similar happened in your case?

**Comment by may215** [comment] 2015-07-19 08:19
Hi,
I am using ubuntu machines and mac, I will try to create the file again, or download .p12 file and try, but, as I said I am using it already in other systems.

**Comment by arikfr** [comment] 2015-07-19 09:02
Please update if it worked or not. Thanks.

**Comment by may215** [comment] 2015-07-19 13:23
No,
I tried all the above suggestions, but, not working.
Any idea?

**Comment by arikfr** [comment] 2015-07-19 13:27
Still getting the same error or a different one?

**Comment by may215** [comment] 2015-07-19 13:34
Hi,
I created the service again from scratch, and now I am getting "Error running query: invalid_grant"..

**Comment by arikfr** [comment] 2015-07-19 13:38
In the service account field, did you use the service account *email*?

**Comment by may215** [comment] 2015-07-19 13:39
Yes, 
I used the service account email and .p12 key

**Comment by may215** [comment] 2015-07-19 13:43
The .env file is owned by root user, and it contain only two properties:
export REDASH_STATIC_ASSETS_PATH="../rd_ui/dist/"
export REDASH_LOG_LEVEL="INFO"
export REDASH_WORKERS_COUNT=6
export REDASH_COOKIE_SECRET=xxxx
export REDASH_GOOGLE_CLIENT_ID=xxxx
export REDASH_GOOGLE_CLIENT_SECRET=xxx

The private key path is:
/opt/redash/current/XXXX.p12

Do I need anything else?

**Comment by arikfr** [comment] 2015-07-19 14:16
I'm not sure if that's why you mentioned the .env file, so I'll clarify just in case: the `REDASH_GOOGLE_CLIENT_ID` and `REDASH_GOOGLE_CLIENT_SECRET` are for the Google OAuth support (used for login) and not related to the BigQuery data source.

Also I suggest not placing the p12 file in the `/opt/redash/current` directory, as it's a symlink to the current version and once you upgrade will be replaced. 

When running: `sudo -u redash bin/run ./manage.py ds new` and selecting "BigQuery" (and not "BigQuery GCE"), you need to supply to the p12 path along with project id and service account email. I only got the "invalid grant" message when I was using invalid service account identifier.

**Comment by arikfr** [comment] 2015-07-19 15:07
Btw, if you generated a new p12 file in Google's developer console, then it creates a new service account email along with it.

**Comment by may215** [comment] 2015-07-19 15:27
Hi,
the .env file: http://redash.io/deployment/setup.html#setup
I have the same service email account for the .p12 file because, as I said I am using it in other services that can connect to this account.

:(

**Comment by arikfr** [comment] 2015-07-19 18:48
Let's continue over email (arik@arikfr.com) -- if you're interested, I would like to either meet if your office is close by to mine, or maybe do a screen share session, to work this out.

**Comment by arikfr** [comment] 2015-08-16 19:17
Closing as I can't reproduce. Also version 0.7 simplified setup of BigQuery datasources, so might help resolve this too.

**Closed by arikfr** 2015-08-16 19:17 UTC
